// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aiot/internal/dao/internal"
	"aiot/internal/model/entity"
	"context"
	"encoding/json"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
)

// adminDao is the data access object for the table admin.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is a globally accessible object for table admin operations.
	Admin = adminDao{internal.NewAdminDao()}
)

const adminCacheTTL = 300

func adminRedisKey(id int64) string { return fmt.Sprintf("admin:%d", id) }

// GetByIdWithCache reads from Redis first, falls back to MySQL.
func (d *adminDao) GetByIdWithCache(ctx context.Context, id int64) (out *entity.Admin, err error) {
	redis := g.Redis()
	key := adminRedisKey(id)
	v, _ := redis.Do(ctx, "GET", key)
	if v != nil && !v.IsNil() && v.String() != "" {
		out = &entity.Admin{}
		if e := json.Unmarshal(v.Bytes(), out); e == nil {
			return out, nil
		}
	}
	var list []*entity.Admin
	err = d.Ctx(ctx).WherePri(id).Where("delete_state", 0).Scan(&list)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	out = list[0]
	b, _ := json.Marshal(out)
	redis.Do(ctx, "SETEX", key, adminCacheTTL, string(b))
	return out, nil
}

// GetByAccount finds an admin by user_account.
func (d *adminDao) GetByAccount(ctx context.Context, account string) (out *entity.Admin, err error) {
	var list []*entity.Admin
	err = d.Ctx(ctx).Where("user_account", account).Where("delete_state", 0).Scan(&list)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	return list[0], nil
}

// InvalidateCache deletes the admin cache entry.
func (d *adminDao) InvalidateCache(ctx context.Context, id int64) {
	g.Redis().Do(ctx, "DEL", adminRedisKey(id))
}
