// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aiot/internal/dao/internal"
	"aiot/internal/model/entity"
	"context"
	"encoding/json"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
)

// boardDao is the data access object for the table board.
type boardDao struct {
	*internal.BoardDao
}

var (
	// Board is a globally accessible object for table board operations.
	Board = boardDao{internal.NewBoardDao()}
)

const boardCacheTTL = 300

func boardRedisKey(id int) string { return fmt.Sprintf("board:%d", id) }

const boardListRedisKey = "board:list"

// GetByIdWithCache reads from Redis first, falls back to MySQL.
func (d *boardDao) GetByIdWithCache(ctx context.Context, id int) (out *entity.Board, err error) {
	redis := g.Redis()
	key := boardRedisKey(id)
	v, _ := redis.Do(ctx, "GET", key)
	if v != nil && !v.IsNil() && v.String() != "" {
		out = &entity.Board{}
		if e := json.Unmarshal(v.Bytes(), out); e == nil {
			return out, nil
		}
	}
	var list []*entity.Board
	err = d.Ctx(ctx).WherePri(id).Scan(&list)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	out = list[0]
	b, _ := json.Marshal(out)
	redis.Do(ctx, "SETEX", key, boardCacheTTL, string(b))
	return out, nil
}

// ListWithCache reads list from Redis first, falls back to MySQL.
func (d *boardDao) ListWithCache(ctx context.Context) (list []*entity.Board, err error) {
	redis := g.Redis()
	v, _ := redis.Do(ctx, "GET", boardListRedisKey)
	if v != nil && !v.IsNil() && v.String() != "" {
		if e := json.Unmarshal(v.Bytes(), &list); e == nil {
			return list, nil
		}
	}
	err = d.Ctx(ctx).Scan(&list)
	if err != nil {
		return nil, err
	}
	b, _ := json.Marshal(list)
	redis.Do(ctx, "SETEX", boardListRedisKey, boardCacheTTL, string(b))
	return list, nil
}

// InvalidateCache deletes single and list cache.
func (d *boardDao) InvalidateCache(ctx context.Context, id int) {
	redis := g.Redis()
	redis.Do(ctx, "DEL", boardRedisKey(id))
	redis.Do(ctx, "DEL", boardListRedisKey)
}
