// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aiot/internal/dao/internal"
	"aiot/internal/model/entity"
	"context"
)

// deviceAlertDao is the data access object for the table device_alert.
type deviceAlertDao struct {
	*internal.DeviceAlertDao
}

var (
	// DeviceAlert is a globally accessible object for table device_alert operations.
	DeviceAlert = deviceAlertDao{internal.NewDeviceAlertDao()}
)

// ListWithFilter returns device alerts with optional filters.
func (d *deviceAlertDao) ListWithFilter(ctx context.Context, status int, alertType int) (list []*entity.DeviceAlert, err error) {
	m := d.Ctx(ctx).OrderDesc("create_time")
	if status >= 0 {
		m = m.Where("status", status)
	}
	if alertType > 0 {
		m = m.Where("alert_type", alertType)
	}
	err = m.Scan(&list)
	return
}

// HasActiveAlert checks if an active (unresolved) alert exists for the given mac and type.
func (d *deviceAlertDao) HasActiveAlert(ctx context.Context, mac string, alertType int) (bool, error) {
	count, err := d.Ctx(ctx).
		Where("mac_address", mac).
		Where("alert_type", alertType).
		Where("status", 0).
		Count()
	return count > 0, err
}
