// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aiot/internal/dao/internal"
	"aiot/internal/model/entity"
	"context"
)

// notificationLogDao is the data access object for the table notification_log.
type notificationLogDao struct {
	*internal.NotificationLogDao
}

var (
	// NotificationLog is a globally accessible object for table notification_log operations.
	NotificationLog = notificationLogDao{internal.NewNotificationLogDao()}
)

// List returns notification logs ordered by create_time desc.
func (d *notificationLogDao) List(ctx context.Context, page, pageSize int) (list []*entity.NotificationLog, total int, err error) {
	m := d.Ctx(ctx).OrderDesc("create_time")
	total, err = m.Count()
	if err != nil {
		return
	}
	if page > 0 && pageSize > 0 {
		m = m.Page(page, pageSize)
	}
	err = m.Scan(&list)
	return
}
