// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aiot/internal/dao/internal"
	"aiot/internal/model/entity"
	"context"
	"encoding/json"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
)

// sensorDao is the data access object for the table sensor.
type sensorDao struct {
	*internal.SensorDao
}

var (
	// Sensor is a globally accessible object for table sensor operations.
	Sensor = sensorDao{internal.NewSensorDao()}
)

const sensorCacheTTL = 300

func sensorKey(id int64) string      { return fmt.Sprintf("sensor:%d", id) }
func sensorMacKey(mac string) string { return fmt.Sprintf("sensor:mac:%s", mac) }

const sensorListKey = "sensor:list"

// GetByIdWithCache reads from Redis first, falls back to MySQL.
func (d *sensorDao) GetByIdWithCache(ctx context.Context, id int64) (out *entity.Sensor, err error) {
	redis := g.Redis()
	key := sensorKey(id)
	v, _ := redis.Do(ctx, "GET", key)
	if v != nil && !v.IsNil() && v.String() != "" {
		out = &entity.Sensor{}
		if e := json.Unmarshal(v.Bytes(), out); e == nil {
			return out, nil
		}
	}
	var list []*entity.Sensor
	err = d.Ctx(ctx).WherePri(id).Scan(&list)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	out = list[0]
	b, _ := json.Marshal(out)
	redis.Do(ctx, "SETEX", key, sensorCacheTTL, string(b))
	return out, nil
}

// GetByMacWithCache reads sensor by MAC from Redis first, falls back to MySQL.
func (d *sensorDao) GetByMacWithCache(ctx context.Context, mac string) (out *entity.Sensor, err error) {
	if mac == "" {
		return nil, nil
	}
	redis := g.Redis()
	key := sensorMacKey(mac)
	v, _ := redis.Do(ctx, "GET", key)
	if v != nil && !v.IsNil() && v.String() != "" {
		return d.GetByIdWithCache(ctx, v.Int64())
	}
	var list []*entity.Sensor
	err = d.Ctx(ctx).Where("mac_address", mac).Limit(1).Scan(&list)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	out = list[0]
	_, _ = redis.Do(ctx, "SETEX", key, sensorCacheTTL, out.Id)
	return d.GetByIdWithCache(ctx, out.Id)
}

// ListWithCache reads list from Redis first, falls back to MySQL.
func (d *sensorDao) ListWithCache(ctx context.Context) (list []*entity.Sensor, err error) {
	redis := g.Redis()
	v, _ := redis.Do(ctx, "GET", sensorListKey)
	if v != nil && !v.IsNil() && v.String() != "" {
		if e := json.Unmarshal(v.Bytes(), &list); e == nil {
			return list, nil
		}
	}
	err = d.Ctx(ctx).Scan(&list)
	if err != nil {
		return nil, err
	}
	b, _ := json.Marshal(list)
	redis.Do(ctx, "SETEX", sensorListKey, sensorCacheTTL, string(b))
	return list, nil
}

// InvalidateCache deletes single, list and mac mapping cache.
func (d *sensorDao) InvalidateCache(ctx context.Context, id int64, macs ...string) {
	redis := g.Redis()
	if id > 0 {
		redis.Do(ctx, "DEL", sensorKey(id))
	}
	redis.Do(ctx, "DEL", sensorListKey)
	for _, mac := range macs {
		if mac != "" {
			redis.Do(ctx, "DEL", sensorMacKey(mac))
		}
	}
}

// GetAllMacs returns all sensor MAC addresses.
func (d *sensorDao) GetAllMacs(ctx context.Context) (macs []string, err error) {
	var sensors []*entity.Sensor
	err = d.Ctx(ctx).Fields("mac_address").Where("status", 1).Scan(&sensors)
	if err != nil {
		return nil, err
	}
	for _, s := range sensors {
		macs = append(macs, s.MacAddress)
	}
	return macs, nil
}
