// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"aiot/internal/dao/internal"
	"aiot/internal/model/entity"
	"context"
	"encoding/json"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
)

// signboardDao is the data access object for the table signboard.
type signboardDao struct {
	*internal.SignboardDao
}

var (
	// Signboard is a globally accessible object for table signboard operations.
	Signboard = signboardDao{internal.NewSignboardDao()}
)

const signboardCacheTTL = 300

func signboardRedisKey(id int64) string { return fmt.Sprintf("signboard:%d", id) }

const signboardListRedisKey = "signboard:list"

// GetByIdWithCache reads from Redis first, falls back to MySQL.
func (d *signboardDao) GetByIdWithCache(ctx context.Context, id int64) (out *entity.Signboard, err error) {
	redis := g.Redis()
	key := signboardRedisKey(id)
	v, _ := redis.Do(ctx, "GET", key)
	if v != nil && !v.IsNil() && v.String() != "" {
		out = &entity.Signboard{}
		if e := json.Unmarshal(v.Bytes(), out); e == nil {
			return out, nil
		}
	}
	var list []*entity.Signboard
	err = d.Ctx(ctx).WherePri(id).Scan(&list)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	out = list[0]
	b, _ := json.Marshal(out)
	redis.Do(ctx, "SETEX", key, signboardCacheTTL, string(b))
	return out, nil
}

// ListWithCache reads list from Redis first, falls back to MySQL.
func (d *signboardDao) ListWithCache(ctx context.Context) (list []*entity.Signboard, err error) {
	redis := g.Redis()
	v, _ := redis.Do(ctx, "GET", signboardListRedisKey)
	if v != nil && !v.IsNil() && v.String() != "" {
		if e := json.Unmarshal(v.Bytes(), &list); e == nil {
			return list, nil
		}
	}
	err = d.Ctx(ctx).Scan(&list)
	if err != nil {
		return nil, err
	}
	b, _ := json.Marshal(list)
	redis.Do(ctx, "SETEX", signboardListRedisKey, signboardCacheTTL, string(b))
	return list, nil
}

// InvalidateCache deletes single and list cache.
func (d *signboardDao) InvalidateCache(ctx context.Context, id int64) {
	redis := g.Redis()
	redis.Do(ctx, "DEL", signboardRedisKey(id))
	redis.Do(ctx, "DEL", signboardListRedisKey)
}

// GetAllMacs returns all signboard MAC addresses.
func (d *signboardDao) GetAllMacs(ctx context.Context) (macs []string, err error) {
	var list []*entity.Signboard
	err = d.Ctx(ctx).Fields("mac_address").Scan(&list)
	if err != nil {
		return nil, err
	}
	for _, sb := range list {
		macs = append(macs, sb.MacAddress)
	}
	return macs, nil
}
