# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/aiot"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app

  build:
    name: "main"
    arch: "amd64"
    system: "linux,windows"
    mod: "none"
    path: "./bin"
    version: "v3.0.0"
